openapi: 3.0.1
info:
  title: API da Atividade 4
  description: API para a Atividade 4.
  version: 0.0.1
  termsOfService: https://mockapi.io
  contact:
    name: Suporte a Devs
    email: contato@example.com
    url: https://mockapi.io
  license:
    name: 'Lincença: GPLv3'
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
  description: Documentação burocrática
  url: https://mockapi.io
servers:
  - url: https://localhost:8080/estados
    description: Atividade 4
paths:
  /partidos:
    get:
      summary: Traz todos os partidos criados
      parameters:
        - in: header
          name: ideologia
          schema:
            type: string
          required: false
          description: Pega os estados por Ideologia
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partido'
    post:
      summary: Cria novo Partido
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Partido'
      responses:
        '201':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partido'
  /partidos/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    get:
      summary: Recupera um Partido pelo ID
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partido'
        '404':
          description: Partido não encontrada
          content:
            application/json:
              example: Not Found
    put:
      summary: Atualiza um Partido
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Partido'
      description: Atualiza um Partido pelo ID
      operationId: id
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partido'
        '404':
          description: Partido não encontrada
          content:
            application/json:
              example: Not Found
          
    delete:
      summary: Deleta um Partido
      description: Atualiza um Partido pelo ID
      operationId: ''
      responses:
        default:
          description: Sucesso
  /partidos/{id}/associados:
     parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
     get:
      summary: Pega os associados de um Partido pelo id do partido
      description: retorna uma lista de associados
      operationId: ID
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Associado'
        '404':
          description: Partido não encontrada
          content:
            application/json:
              example: Not Found
  /associados:
    get:
      summary: Traz todos os associados criados
      parameters:
        - in: header
          name: Cargo
          schema:
            type: string
          required: false
          description: Pega os associados por cargo politico
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Associado'
    post:
      summary: Cria novo Associado
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Associado'
      responses:
        '201':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Associado'
  /associados/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    get:
      summary: Recupera um Associado pelo ID
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Associado'
        '404':
          description: Associado não encontrada
          content:
            application/json:
              example: Not Found
    put:
      summary: Atualiza um Associado
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Associado'
      description: Atualiza um Associado pelo ID
      operationId: DI
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Associado'
        '404':
          description: Associado não encontrada
          content:
            application/json:
              example: Not Found
          
    delete:
      summary: Deleta um Associado
      description: Deleta um Associado pelo ID
      operationId: ''
      responses:
        default:
          description: Sucesso
  /associados/partido/:
     parameters:
      - name: id
        in: query
        schema:
          type: integer
        required: true
     post:
      summary: Vincula um associado com um Partido
      description: Vincula um associado com um partido
      operationId: IDs
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Associado'
        '404':
          description: Partido não encontrada
          content:
            application/json:
              example: Not Found
  /associados/{id}/partidos/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    delete:
      summary: Remove determinado associado daquele partido
      description: Deleta um Associado pelo ID e ID do partido
      operationId: ''
      responses:
        default:
          description: Sucesso
security:
  - auth: []
components:
  schemas:
    Partido:
      type: object
      properties:
        id:
          type: integer
        Sigla:
          type: string
        Ideologia:
          type: string
        dataFundacao:
          type: string
        Associados:
          type: string
    Associado:
      type: object
      properties:
        id:
          type: integer
        Nome:
          type: string
        Cargo Politico:
          type: string
        dataNascimento:
          type: string
        Genero:
          type: string
        Partido:
          type: string
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
